- hosts: server2
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Copy this playbook to another server
      action: copy src=copy.yml dest=/tmp/playbook.yml owner=root group=root mode=0777 backup=yes
