- hosts: slaves
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Backup fstab
      fetch:
        src: /etc/fstab
        dest: conf/fstab_backup/{{ ansible_hostname }}
        flat: yes
