- hosts: centos
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Ensure that 'git' is installed
      yum: name=git state=latest
    - name: Clone an example git repo to /tmp
      git:
        repo: https://github.com/rpm-software-management/deltarpm.git
        dest: /tmp/deltarpm
        update: yes
