--- # IMPORTANT NOTE
    # As I did NOT want to blacklist any crucial kernel module,
    # I decided to blacklist the 'dummy' module.
    # You can try to disable an used module,
    # but please bear in mind that you do so AT YOUR OWN RISK.
    # Thus, do NOT open an issue to solve a problem that YOU just created.
- hosts: slaves
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Blacklist 'dummy' kernel module
      kernel_blacklist: name=dummy state=present
