--- # Sample archive includes one dir called sample
    # with 9 files - sample{1,2,3,4,5,6,7,8,9}.txt
- hosts: slaves
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Copy and unarchive a sample archive
      unarchive: src=conf/sample.tar.gz dest=/tmp list_files=true
      register: unarchive
    - debug: var=unarchive.files
