- hosts: centos
  sudo: yes
  gather_facts: no
  tasks:
    - name: Ensure that tomcat is in the lastest version
      yum: pkg=tomcat state=latest update_cache=true
    - name: Ensure that tomcat is started
      service: name=tomcat state=started
    - name: Wait for port 8080 to listen
      wait_for:
        port: 8080
        state: started
    - name: When port 8080 starts listening, install lynx
      yum: pkg=lynx state=latest
