--- # Outline to playbook
- hosts: apache
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - name: Date/time stamp for when the playbook starts
      raw: /usr/bin/date > /home/ansible/playbook_start.log
    - name: Install the apache web server
      yum: pkg=httpd state=latest
    - name: Start the web service
      service: name=httpd state=restarted
    - name: Verify that the web service is running
      command: systemctl status httpd
      register: result
    - debug: var=result
    - name: Install client software - telnet
      yum: pkg=telnet state=latest
    - name: Install client software - lynx
      yum: pkg=lynx state=latest
    - name: Log all installed packages
      raw: yum list installed > /home/ansible/installed.log
    - name: date/time stamp for when the playbook ends
      raw: /usr/bin/date > /home/ansible/playbook_end.log
