- hosts: slaves
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  pre_tasks:
    - name: Log playbook start uptime
      raw: uptime > conditional_start.log
  roles:
    - { role: debian_apache, when: ansible_os_family == 'Debian' }
    - { role: redhat_apache, when: ansible_os_family == 'RedHat' }
  post_tasks:
    - name: Log playbook end uptime
      raw: uptime > conditional_end.log
