- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
- name: Install apache
  apt:
    name: apache2
    state: latest
- name: Ensure that apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
