- hosts: slaves
  user: test
  sudo: yes
  connection: ssh
  tasks:
    - name: Install Apache on Debian/Ubuntu
      command: apt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: Install Apache on RedHat/CentOS
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
