- hosts: apache
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
    - name: Verify the Lynx Web Browser
      action: yum name=lynx state=installed
