- hosts: slaves
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: Local username
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      notify: Restart httpd
  handlers:
    - name: Restart httpd
      action: service name=httpd state=restarted
