- hosts: centos:ubuntu
  connection: ssh
  user: test
  sudo: yes
  gather_facts: yes
  vars:
    user_name: test
    user_password: password123
    connection_type: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=conf/test.conf.j2 dest=/home/test/test.conf owner=test group=test mode=750
