- hosts: centos
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - debug: msg="The number and atomic mass of Lithium is {{ lookup('csvfile', 'Li file=conf/sample.csv delimiter=, col=2,3') }}"
