--- # Run using ansible-playbook start_at.yml --start-at-task="Install lynx"
- hosts: centos
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet
      yum: pkg=telnet state=latest
    - name: Install lynx
      yum: pkg=lynx state=latest
    - name: List home
      command: ls -al /home/test
      register: home_list
    - debug: var=result
