--- # To just install lynx you can try:
    # ansible-playbook --tags "install_lynx" tags.yml
    # or ansible-playbook --skip-tags "install_telnet" tags.yml
- hosts: centos
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet
      yum: pkg=telnet state=latest
      tags:
        - install_telnet
    - name: Install lynx
      yum: pkg=lynx state=latest
      tags:
        - install_lynx
