--- # Run using:
    # ansible-playbook --extra-vars "hosts=centos user=test pkg=telnet" vars_commandline.yml
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the specified package
      yum: pkg='{{ pkg }}' state=latest
