- hosts: slaves
  vars:
    control_server: 172.31.102.77
    web_root: /var/www/html
  vars_files:
    - conf/weird_var.yml
  tasks:
    - name: Install Lynx on all slaves
      yum: pkg=lynx state=installed update_cache=true
